# Generated by Django 2.1.5 on 2019-03-11 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='tasktime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
