# Generated by Django 2.1.5 on 2019-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_tasktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tasktime',
            field=models.TimeField(default='10:48 AM'),
        ),
    ]
